/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SynergisticProtocolRouteImport } from './routes/synergistic-protocol'
import { Route as StudentRouteImport } from './routes/student'
import { Route as PendingReviewRouteImport } from './routes/pending-review'
import { Route as LichKhaiGiangRouteImport } from './routes/lich-khai-giang'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as BatchesIndexRouteImport } from './routes/batches.index'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as KhoaHocSlugRouteImport } from './routes/khoa-hoc.$slug'
import { Route as GiangVienSlugRouteImport } from './routes/giang-vien.$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as BatchesSlugRouteImport } from './routes/batches.$slug'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth.verify-otp'
import { Route as AuthPhoneRouteImport } from './routes/auth.phone'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminInstructorsRouteImport } from './routes/admin.instructors'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminAcademyStudentsRouteImport } from './routes/admin.academy-students'
import { Route as AdminAcademyLandingsRouteImport } from './routes/admin.academy-landings'
import { Route as AdminAcademyEnrollmentsRouteImport } from './routes/admin.academy-enrollments'
import { Route as AdminAcademyCategoriesRouteImport } from './routes/admin.academy-categories'
import { Route as AdminAcademyAccessRouteImport } from './routes/admin.academy-access'
import { Route as StudentCoursesIndexRouteImport } from './routes/student.courses.index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin.courses.index'
import { Route as AdminBatchesIndexRouteImport } from './routes/admin.batches.index'
import { Route as AdminCoursesNewRouteImport } from './routes/admin.courses.new'
import { Route as AdminCoursesCourseIdRouteImport } from './routes/admin.courses.$courseId'
import { Route as AdminBatchesNewRouteImport } from './routes/admin.batches.new'
import { Route as AdminBatchesBatchIdRouteImport } from './routes/admin.batches.$batchId'
import { Route as AdminCoursesCourseIdIndexRouteImport } from './routes/admin.courses.$courseId.index'
import { Route as AdminBatchesBatchIdIndexRouteImport } from './routes/admin.batches.$batchId.index'
import { Route as AdminCoursesCourseIdSettingsRouteImport } from './routes/admin.courses.$courseId.settings'
import { Route as AdminCoursesCourseIdContentRouteImport } from './routes/admin.courses.$courseId.content'
import { Route as AdminBatchesBatchIdRegistrationsRouteImport } from './routes/admin.batches.$batchId.registrations'
import { Route as AdminAcademyLandingsSlugPreviewRouteImport } from './routes/admin.academy-landings.$slug.preview'
import { Route as StudentCoursesSlugLessonsLessonIdRouteImport } from './routes/student.courses.$slug.lessons.$lessonId'

const SynergisticProtocolRoute = SynergisticProtocolRouteImport.update({
  id: '/synergistic-protocol',
  path: '/synergistic-protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingReviewRoute = PendingReviewRouteImport.update({
  id: '/pending-review',
  path: '/pending-review',
  getParentRoute: () => rootRouteImport,
} as any)
const LichKhaiGiangRoute = LichKhaiGiangRouteImport.update({
  id: '/lich-khai-giang',
  path: '/lich-khai-giang',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const BatchesIndexRoute = BatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KhoaHocSlugRoute = KhoaHocSlugRouteImport.update({
  id: '/khoa-hoc/$slug',
  path: '/khoa-hoc/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GiangVienSlugRoute = GiangVienSlugRouteImport.update({
  id: '/giang-vien/$slug',
  path: '/giang-vien/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const BatchesSlugRoute = BatchesSlugRouteImport.update({
  id: '/batches/$slug',
  path: '/batches/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/auth/verify-otp',
  path: '/auth/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPhoneRoute = AuthPhoneRouteImport.update({
  id: '/auth/phone',
  path: '/auth/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstructorsRoute = AdminInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademyStudentsRoute = AdminAcademyStudentsRouteImport.update({
  id: '/academy-students',
  path: '/academy-students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademyLandingsRoute = AdminAcademyLandingsRouteImport.update({
  id: '/academy-landings',
  path: '/academy-landings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademyEnrollmentsRoute = AdminAcademyEnrollmentsRouteImport.update({
  id: '/academy-enrollments',
  path: '/academy-enrollments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademyCategoriesRoute = AdminAcademyCategoriesRouteImport.update({
  id: '/academy-categories',
  path: '/academy-categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademyAccessRoute = AdminAcademyAccessRouteImport.update({
  id: '/academy-access',
  path: '/academy-access',
  getParentRoute: () => AdminRoute,
} as any)
const StudentCoursesIndexRoute = StudentCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentCoursesRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBatchesIndexRoute = AdminBatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesNewRoute = AdminCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesCourseIdRoute = AdminCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBatchesNewRoute = AdminBatchesNewRouteImport.update({
  id: '/batches/new',
  path: '/batches/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBatchesBatchIdRoute = AdminBatchesBatchIdRouteImport.update({
  id: '/batches/$batchId',
  path: '/batches/$batchId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesCourseIdIndexRoute =
  AdminCoursesCourseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminCoursesCourseIdRoute,
  } as any)
const AdminBatchesBatchIdIndexRoute =
  AdminBatchesBatchIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminBatchesBatchIdRoute,
  } as any)
const AdminCoursesCourseIdSettingsRoute =
  AdminCoursesCourseIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminCoursesCourseIdRoute,
  } as any)
const AdminCoursesCourseIdContentRoute =
  AdminCoursesCourseIdContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AdminCoursesCourseIdRoute,
  } as any)
const AdminBatchesBatchIdRegistrationsRoute =
  AdminBatchesBatchIdRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => AdminBatchesBatchIdRoute,
  } as any)
const AdminAcademyLandingsSlugPreviewRoute =
  AdminAcademyLandingsSlugPreviewRouteImport.update({
    id: '/$slug/preview',
    path: '/$slug/preview',
    getParentRoute: () => AdminAcademyLandingsRoute,
  } as any)
const StudentCoursesSlugLessonsLessonIdRoute =
  StudentCoursesSlugLessonsLessonIdRouteImport.update({
    id: '/$slug/lessons/$lessonId',
    path: '/$slug/lessons/$lessonId',
    getParentRoute: () => StudentCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blocked': typeof BlockedRoute
  '/courses': typeof CoursesRouteWithChildren
  '/lich-khai-giang': typeof LichKhaiGiangRoute
  '/pending-review': typeof PendingReviewRoute
  '/student': typeof StudentRouteWithChildren
  '/synergistic-protocol': typeof SynergisticProtocolRoute
  '/admin/academy-access': typeof AdminAcademyAccessRoute
  '/admin/academy-categories': typeof AdminAcademyCategoriesRoute
  '/admin/academy-enrollments': typeof AdminAcademyEnrollmentsRoute
  '/admin/academy-landings': typeof AdminAcademyLandingsRouteWithChildren
  '/admin/academy-students': typeof AdminAcademyStudentsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/batches/$slug': typeof BatchesSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/giang-vien/$slug': typeof GiangVienSlugRoute
  '/khoa-hoc/$slug': typeof KhoaHocSlugRoute
  '/l/$slug': typeof LSlugRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/profile': typeof StudentProfileRoute
  '/batches/': typeof BatchesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/batches/$batchId': typeof AdminBatchesBatchIdRouteWithChildren
  '/admin/batches/new': typeof AdminBatchesNewRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRouteWithChildren
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/batches/': typeof AdminBatchesIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/student/courses/': typeof StudentCoursesIndexRoute
  '/admin/academy-landings/$slug/preview': typeof AdminAcademyLandingsSlugPreviewRoute
  '/admin/batches/$batchId/registrations': typeof AdminBatchesBatchIdRegistrationsRoute
  '/admin/courses/$courseId/content': typeof AdminCoursesCourseIdContentRoute
  '/admin/courses/$courseId/settings': typeof AdminCoursesCourseIdSettingsRoute
  '/admin/batches/$batchId/': typeof AdminBatchesBatchIdIndexRoute
  '/admin/courses/$courseId/': typeof AdminCoursesCourseIdIndexRoute
  '/student/courses/$slug/lessons/$lessonId': typeof StudentCoursesSlugLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blocked': typeof BlockedRoute
  '/lich-khai-giang': typeof LichKhaiGiangRoute
  '/pending-review': typeof PendingReviewRoute
  '/synergistic-protocol': typeof SynergisticProtocolRoute
  '/admin/academy-access': typeof AdminAcademyAccessRoute
  '/admin/academy-categories': typeof AdminAcademyCategoriesRoute
  '/admin/academy-enrollments': typeof AdminAcademyEnrollmentsRoute
  '/admin/academy-landings': typeof AdminAcademyLandingsRouteWithChildren
  '/admin/academy-students': typeof AdminAcademyStudentsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/batches/$slug': typeof BatchesSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/giang-vien/$slug': typeof GiangVienSlugRoute
  '/khoa-hoc/$slug': typeof KhoaHocSlugRoute
  '/l/$slug': typeof LSlugRoute
  '/student/profile': typeof StudentProfileRoute
  '/batches': typeof BatchesIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/batches/new': typeof AdminBatchesNewRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/batches': typeof AdminBatchesIndexRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/student/courses': typeof StudentCoursesIndexRoute
  '/admin/academy-landings/$slug/preview': typeof AdminAcademyLandingsSlugPreviewRoute
  '/admin/batches/$batchId/registrations': typeof AdminBatchesBatchIdRegistrationsRoute
  '/admin/courses/$courseId/content': typeof AdminCoursesCourseIdContentRoute
  '/admin/courses/$courseId/settings': typeof AdminCoursesCourseIdSettingsRoute
  '/admin/batches/$batchId': typeof AdminBatchesBatchIdIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdIndexRoute
  '/student/courses/$slug/lessons/$lessonId': typeof StudentCoursesSlugLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blocked': typeof BlockedRoute
  '/courses': typeof CoursesRouteWithChildren
  '/lich-khai-giang': typeof LichKhaiGiangRoute
  '/pending-review': typeof PendingReviewRoute
  '/student': typeof StudentRouteWithChildren
  '/synergistic-protocol': typeof SynergisticProtocolRoute
  '/admin/academy-access': typeof AdminAcademyAccessRoute
  '/admin/academy-categories': typeof AdminAcademyCategoriesRoute
  '/admin/academy-enrollments': typeof AdminAcademyEnrollmentsRoute
  '/admin/academy-landings': typeof AdminAcademyLandingsRouteWithChildren
  '/admin/academy-students': typeof AdminAcademyStudentsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/batches/$slug': typeof BatchesSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/giang-vien/$slug': typeof GiangVienSlugRoute
  '/khoa-hoc/$slug': typeof KhoaHocSlugRoute
  '/l/$slug': typeof LSlugRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/profile': typeof StudentProfileRoute
  '/batches/': typeof BatchesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/batches/$batchId': typeof AdminBatchesBatchIdRouteWithChildren
  '/admin/batches/new': typeof AdminBatchesNewRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRouteWithChildren
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/batches/': typeof AdminBatchesIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/student/courses/': typeof StudentCoursesIndexRoute
  '/admin/academy-landings/$slug/preview': typeof AdminAcademyLandingsSlugPreviewRoute
  '/admin/batches/$batchId/registrations': typeof AdminBatchesBatchIdRegistrationsRoute
  '/admin/courses/$courseId/content': typeof AdminCoursesCourseIdContentRoute
  '/admin/courses/$courseId/settings': typeof AdminCoursesCourseIdSettingsRoute
  '/admin/batches/$batchId/': typeof AdminBatchesBatchIdIndexRoute
  '/admin/courses/$courseId/': typeof AdminCoursesCourseIdIndexRoute
  '/student/courses/$slug/lessons/$lessonId': typeof StudentCoursesSlugLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blocked'
    | '/courses'
    | '/lich-khai-giang'
    | '/pending-review'
    | '/student'
    | '/synergistic-protocol'
    | '/admin/academy-access'
    | '/admin/academy-categories'
    | '/admin/academy-enrollments'
    | '/admin/academy-landings'
    | '/admin/academy-students'
    | '/admin/calendar'
    | '/admin/instructors'
    | '/admin/notifications'
    | '/auth/login'
    | '/auth/phone'
    | '/auth/verify-otp'
    | '/batches/$slug'
    | '/courses/$slug'
    | '/giang-vien/$slug'
    | '/khoa-hoc/$slug'
    | '/l/$slug'
    | '/student/courses'
    | '/student/profile'
    | '/batches/'
    | '/courses/'
    | '/student/'
    | '/admin/batches/$batchId'
    | '/admin/batches/new'
    | '/admin/courses/$courseId'
    | '/admin/courses/new'
    | '/admin/batches/'
    | '/admin/courses/'
    | '/student/courses/'
    | '/admin/academy-landings/$slug/preview'
    | '/admin/batches/$batchId/registrations'
    | '/admin/courses/$courseId/content'
    | '/admin/courses/$courseId/settings'
    | '/admin/batches/$batchId/'
    | '/admin/courses/$courseId/'
    | '/student/courses/$slug/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blocked'
    | '/lich-khai-giang'
    | '/pending-review'
    | '/synergistic-protocol'
    | '/admin/academy-access'
    | '/admin/academy-categories'
    | '/admin/academy-enrollments'
    | '/admin/academy-landings'
    | '/admin/academy-students'
    | '/admin/calendar'
    | '/admin/instructors'
    | '/admin/notifications'
    | '/auth/login'
    | '/auth/phone'
    | '/auth/verify-otp'
    | '/batches/$slug'
    | '/courses/$slug'
    | '/giang-vien/$slug'
    | '/khoa-hoc/$slug'
    | '/l/$slug'
    | '/student/profile'
    | '/batches'
    | '/courses'
    | '/student'
    | '/admin/batches/new'
    | '/admin/courses/new'
    | '/admin/batches'
    | '/admin/courses'
    | '/student/courses'
    | '/admin/academy-landings/$slug/preview'
    | '/admin/batches/$batchId/registrations'
    | '/admin/courses/$courseId/content'
    | '/admin/courses/$courseId/settings'
    | '/admin/batches/$batchId'
    | '/admin/courses/$courseId'
    | '/student/courses/$slug/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blocked'
    | '/courses'
    | '/lich-khai-giang'
    | '/pending-review'
    | '/student'
    | '/synergistic-protocol'
    | '/admin/academy-access'
    | '/admin/academy-categories'
    | '/admin/academy-enrollments'
    | '/admin/academy-landings'
    | '/admin/academy-students'
    | '/admin/calendar'
    | '/admin/instructors'
    | '/admin/notifications'
    | '/auth/login'
    | '/auth/phone'
    | '/auth/verify-otp'
    | '/batches/$slug'
    | '/courses/$slug'
    | '/giang-vien/$slug'
    | '/khoa-hoc/$slug'
    | '/l/$slug'
    | '/student/courses'
    | '/student/profile'
    | '/batches/'
    | '/courses/'
    | '/student/'
    | '/admin/batches/$batchId'
    | '/admin/batches/new'
    | '/admin/courses/$courseId'
    | '/admin/courses/new'
    | '/admin/batches/'
    | '/admin/courses/'
    | '/student/courses/'
    | '/admin/academy-landings/$slug/preview'
    | '/admin/batches/$batchId/registrations'
    | '/admin/courses/$courseId/content'
    | '/admin/courses/$courseId/settings'
    | '/admin/batches/$batchId/'
    | '/admin/courses/$courseId/'
    | '/student/courses/$slug/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlockedRoute: typeof BlockedRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  LichKhaiGiangRoute: typeof LichKhaiGiangRoute
  PendingReviewRoute: typeof PendingReviewRoute
  StudentRoute: typeof StudentRouteWithChildren
  SynergisticProtocolRoute: typeof SynergisticProtocolRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPhoneRoute: typeof AuthPhoneRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
  BatchesSlugRoute: typeof BatchesSlugRoute
  GiangVienSlugRoute: typeof GiangVienSlugRoute
  KhoaHocSlugRoute: typeof KhoaHocSlugRoute
  LSlugRoute: typeof LSlugRoute
  BatchesIndexRoute: typeof BatchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/synergistic-protocol': {
      id: '/synergistic-protocol'
      path: '/synergistic-protocol'
      fullPath: '/synergistic-protocol'
      preLoaderRoute: typeof SynergisticProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-review': {
      id: '/pending-review'
      path: '/pending-review'
      fullPath: '/pending-review'
      preLoaderRoute: typeof PendingReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lich-khai-giang': {
      id: '/lich-khai-giang'
      path: '/lich-khai-giang'
      fullPath: '/lich-khai-giang'
      preLoaderRoute: typeof LichKhaiGiangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/batches/': {
      id: '/batches/'
      path: '/batches'
      fullPath: '/batches/'
      preLoaderRoute: typeof BatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khoa-hoc/$slug': {
      id: '/khoa-hoc/$slug'
      path: '/khoa-hoc/$slug'
      fullPath: '/khoa-hoc/$slug'
      preLoaderRoute: typeof KhoaHocSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giang-vien/$slug': {
      id: '/giang-vien/$slug'
      path: '/giang-vien/$slug'
      fullPath: '/giang-vien/$slug'
      preLoaderRoute: typeof GiangVienSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/batches/$slug': {
      id: '/batches/$slug'
      path: '/batches/$slug'
      fullPath: '/batches/$slug'
      preLoaderRoute: typeof BatchesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/auth/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/phone': {
      id: '/auth/phone'
      path: '/auth/phone'
      fullPath: '/auth/phone'
      preLoaderRoute: typeof AuthPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instructors': {
      id: '/admin/instructors'
      path: '/instructors'
      fullPath: '/admin/instructors'
      preLoaderRoute: typeof AdminInstructorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academy-students': {
      id: '/admin/academy-students'
      path: '/academy-students'
      fullPath: '/admin/academy-students'
      preLoaderRoute: typeof AdminAcademyStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academy-landings': {
      id: '/admin/academy-landings'
      path: '/academy-landings'
      fullPath: '/admin/academy-landings'
      preLoaderRoute: typeof AdminAcademyLandingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academy-enrollments': {
      id: '/admin/academy-enrollments'
      path: '/academy-enrollments'
      fullPath: '/admin/academy-enrollments'
      preLoaderRoute: typeof AdminAcademyEnrollmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academy-categories': {
      id: '/admin/academy-categories'
      path: '/academy-categories'
      fullPath: '/admin/academy-categories'
      preLoaderRoute: typeof AdminAcademyCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academy-access': {
      id: '/admin/academy-access'
      path: '/academy-access'
      fullPath: '/admin/academy-access'
      preLoaderRoute: typeof AdminAcademyAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/courses/': {
      id: '/student/courses/'
      path: '/'
      fullPath: '/student/courses/'
      preLoaderRoute: typeof StudentCoursesIndexRouteImport
      parentRoute: typeof StudentCoursesRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/batches/': {
      id: '/admin/batches/'
      path: '/batches'
      fullPath: '/admin/batches/'
      preLoaderRoute: typeof AdminBatchesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/new': {
      id: '/admin/courses/new'
      path: '/courses/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AdminCoursesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/$courseId': {
      id: '/admin/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AdminCoursesCourseIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/batches/new': {
      id: '/admin/batches/new'
      path: '/batches/new'
      fullPath: '/admin/batches/new'
      preLoaderRoute: typeof AdminBatchesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/batches/$batchId': {
      id: '/admin/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/admin/batches/$batchId'
      preLoaderRoute: typeof AdminBatchesBatchIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/$courseId/': {
      id: '/admin/courses/$courseId/'
      path: '/'
      fullPath: '/admin/courses/$courseId/'
      preLoaderRoute: typeof AdminCoursesCourseIdIndexRouteImport
      parentRoute: typeof AdminCoursesCourseIdRoute
    }
    '/admin/batches/$batchId/': {
      id: '/admin/batches/$batchId/'
      path: '/'
      fullPath: '/admin/batches/$batchId/'
      preLoaderRoute: typeof AdminBatchesBatchIdIndexRouteImport
      parentRoute: typeof AdminBatchesBatchIdRoute
    }
    '/admin/courses/$courseId/settings': {
      id: '/admin/courses/$courseId/settings'
      path: '/settings'
      fullPath: '/admin/courses/$courseId/settings'
      preLoaderRoute: typeof AdminCoursesCourseIdSettingsRouteImport
      parentRoute: typeof AdminCoursesCourseIdRoute
    }
    '/admin/courses/$courseId/content': {
      id: '/admin/courses/$courseId/content'
      path: '/content'
      fullPath: '/admin/courses/$courseId/content'
      preLoaderRoute: typeof AdminCoursesCourseIdContentRouteImport
      parentRoute: typeof AdminCoursesCourseIdRoute
    }
    '/admin/batches/$batchId/registrations': {
      id: '/admin/batches/$batchId/registrations'
      path: '/registrations'
      fullPath: '/admin/batches/$batchId/registrations'
      preLoaderRoute: typeof AdminBatchesBatchIdRegistrationsRouteImport
      parentRoute: typeof AdminBatchesBatchIdRoute
    }
    '/admin/academy-landings/$slug/preview': {
      id: '/admin/academy-landings/$slug/preview'
      path: '/$slug/preview'
      fullPath: '/admin/academy-landings/$slug/preview'
      preLoaderRoute: typeof AdminAcademyLandingsSlugPreviewRouteImport
      parentRoute: typeof AdminAcademyLandingsRoute
    }
    '/student/courses/$slug/lessons/$lessonId': {
      id: '/student/courses/$slug/lessons/$lessonId'
      path: '/$slug/lessons/$lessonId'
      fullPath: '/student/courses/$slug/lessons/$lessonId'
      preLoaderRoute: typeof StudentCoursesSlugLessonsLessonIdRouteImport
      parentRoute: typeof StudentCoursesRoute
    }
  }
}

interface AdminAcademyLandingsRouteChildren {
  AdminAcademyLandingsSlugPreviewRoute: typeof AdminAcademyLandingsSlugPreviewRoute
}

const AdminAcademyLandingsRouteChildren: AdminAcademyLandingsRouteChildren = {
  AdminAcademyLandingsSlugPreviewRoute: AdminAcademyLandingsSlugPreviewRoute,
}

const AdminAcademyLandingsRouteWithChildren =
  AdminAcademyLandingsRoute._addFileChildren(AdminAcademyLandingsRouteChildren)

interface AdminBatchesBatchIdRouteChildren {
  AdminBatchesBatchIdRegistrationsRoute: typeof AdminBatchesBatchIdRegistrationsRoute
  AdminBatchesBatchIdIndexRoute: typeof AdminBatchesBatchIdIndexRoute
}

const AdminBatchesBatchIdRouteChildren: AdminBatchesBatchIdRouteChildren = {
  AdminBatchesBatchIdRegistrationsRoute: AdminBatchesBatchIdRegistrationsRoute,
  AdminBatchesBatchIdIndexRoute: AdminBatchesBatchIdIndexRoute,
}

const AdminBatchesBatchIdRouteWithChildren =
  AdminBatchesBatchIdRoute._addFileChildren(AdminBatchesBatchIdRouteChildren)

interface AdminCoursesCourseIdRouteChildren {
  AdminCoursesCourseIdContentRoute: typeof AdminCoursesCourseIdContentRoute
  AdminCoursesCourseIdSettingsRoute: typeof AdminCoursesCourseIdSettingsRoute
  AdminCoursesCourseIdIndexRoute: typeof AdminCoursesCourseIdIndexRoute
}

const AdminCoursesCourseIdRouteChildren: AdminCoursesCourseIdRouteChildren = {
  AdminCoursesCourseIdContentRoute: AdminCoursesCourseIdContentRoute,
  AdminCoursesCourseIdSettingsRoute: AdminCoursesCourseIdSettingsRoute,
  AdminCoursesCourseIdIndexRoute: AdminCoursesCourseIdIndexRoute,
}

const AdminCoursesCourseIdRouteWithChildren =
  AdminCoursesCourseIdRoute._addFileChildren(AdminCoursesCourseIdRouteChildren)

interface AdminRouteChildren {
  AdminAcademyAccessRoute: typeof AdminAcademyAccessRoute
  AdminAcademyCategoriesRoute: typeof AdminAcademyCategoriesRoute
  AdminAcademyEnrollmentsRoute: typeof AdminAcademyEnrollmentsRoute
  AdminAcademyLandingsRoute: typeof AdminAcademyLandingsRouteWithChildren
  AdminAcademyStudentsRoute: typeof AdminAcademyStudentsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminInstructorsRoute: typeof AdminInstructorsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminBatchesBatchIdRoute: typeof AdminBatchesBatchIdRouteWithChildren
  AdminBatchesNewRoute: typeof AdminBatchesNewRoute
  AdminCoursesCourseIdRoute: typeof AdminCoursesCourseIdRouteWithChildren
  AdminCoursesNewRoute: typeof AdminCoursesNewRoute
  AdminBatchesIndexRoute: typeof AdminBatchesIndexRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcademyAccessRoute: AdminAcademyAccessRoute,
  AdminAcademyCategoriesRoute: AdminAcademyCategoriesRoute,
  AdminAcademyEnrollmentsRoute: AdminAcademyEnrollmentsRoute,
  AdminAcademyLandingsRoute: AdminAcademyLandingsRouteWithChildren,
  AdminAcademyStudentsRoute: AdminAcademyStudentsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminInstructorsRoute: AdminInstructorsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminBatchesBatchIdRoute: AdminBatchesBatchIdRouteWithChildren,
  AdminBatchesNewRoute: AdminBatchesNewRoute,
  AdminCoursesCourseIdRoute: AdminCoursesCourseIdRouteWithChildren,
  AdminCoursesNewRoute: AdminCoursesNewRoute,
  AdminBatchesIndexRoute: AdminBatchesIndexRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface StudentCoursesRouteChildren {
  StudentCoursesIndexRoute: typeof StudentCoursesIndexRoute
  StudentCoursesSlugLessonsLessonIdRoute: typeof StudentCoursesSlugLessonsLessonIdRoute
}

const StudentCoursesRouteChildren: StudentCoursesRouteChildren = {
  StudentCoursesIndexRoute: StudentCoursesIndexRoute,
  StudentCoursesSlugLessonsLessonIdRoute:
    StudentCoursesSlugLessonsLessonIdRoute,
}

const StudentCoursesRouteWithChildren = StudentCoursesRoute._addFileChildren(
  StudentCoursesRouteChildren,
)

interface StudentRouteChildren {
  StudentCoursesRoute: typeof StudentCoursesRouteWithChildren
  StudentProfileRoute: typeof StudentProfileRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCoursesRoute: StudentCoursesRouteWithChildren,
  StudentProfileRoute: StudentProfileRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlockedRoute: BlockedRoute,
  CoursesRoute: CoursesRouteWithChildren,
  LichKhaiGiangRoute: LichKhaiGiangRoute,
  PendingReviewRoute: PendingReviewRoute,
  StudentRoute: StudentRouteWithChildren,
  SynergisticProtocolRoute: SynergisticProtocolRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPhoneRoute: AuthPhoneRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
  BatchesSlugRoute: BatchesSlugRoute,
  GiangVienSlugRoute: GiangVienSlugRoute,
  KhoaHocSlugRoute: KhoaHocSlugRoute,
  LSlugRoute: LSlugRoute,
  BatchesIndexRoute: BatchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
