/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth.verify-otp'
import { Route as AuthPhoneRouteImport } from './routes/auth.phone'
import { Route as StudentCoursesSlugLessonsLessonIdRouteImport } from './routes/student.courses.$slug.lessons.$lessonId'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/auth/verify-otp',
  path: '/auth/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPhoneRoute = AuthPhoneRouteImport.update({
  id: '/auth/phone',
  path: '/auth/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesSlugLessonsLessonIdRoute =
  StudentCoursesSlugLessonsLessonIdRouteImport.update({
    id: '/$slug/lessons/$lessonId',
    path: '/$slug/lessons/$lessonId',
    getParentRoute: () => StudentCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courses': typeof CoursesRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/auth/phone': typeof AuthPhoneRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/profile': typeof StudentProfileRoute
  '/student/': typeof StudentIndexRoute
  '/student/courses/$slug/lessons/$lessonId': typeof StudentCoursesSlugLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courses': typeof CoursesRouteWithChildren
  '/auth/phone': typeof AuthPhoneRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/profile': typeof StudentProfileRoute
  '/student': typeof StudentIndexRoute
  '/student/courses/$slug/lessons/$lessonId': typeof StudentCoursesSlugLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courses': typeof CoursesRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/auth/phone': typeof AuthPhoneRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/profile': typeof StudentProfileRoute
  '/student/': typeof StudentIndexRoute
  '/student/courses/$slug/lessons/$lessonId': typeof StudentCoursesSlugLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/courses'
    | '/student'
    | '/auth/phone'
    | '/auth/verify-otp'
    | '/courses/$slug'
    | '/student/courses'
    | '/student/profile'
    | '/student/'
    | '/student/courses/$slug/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/courses'
    | '/auth/phone'
    | '/auth/verify-otp'
    | '/courses/$slug'
    | '/student/courses'
    | '/student/profile'
    | '/student'
    | '/student/courses/$slug/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/courses'
    | '/student'
    | '/auth/phone'
    | '/auth/verify-otp'
    | '/courses/$slug'
    | '/student/courses'
    | '/student/profile'
    | '/student/'
    | '/student/courses/$slug/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  AuthPhoneRoute: typeof AuthPhoneRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/auth/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/phone': {
      id: '/auth/phone'
      path: '/auth/phone'
      fullPath: '/auth/phone'
      preLoaderRoute: typeof AuthPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses/$slug/lessons/$lessonId': {
      id: '/student/courses/$slug/lessons/$lessonId'
      path: '/$slug/lessons/$lessonId'
      fullPath: '/student/courses/$slug/lessons/$lessonId'
      preLoaderRoute: typeof StudentCoursesSlugLessonsLessonIdRouteImport
      parentRoute: typeof StudentCoursesRoute
    }
  }
}

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface StudentCoursesRouteChildren {
  StudentCoursesSlugLessonsLessonIdRoute: typeof StudentCoursesSlugLessonsLessonIdRoute
}

const StudentCoursesRouteChildren: StudentCoursesRouteChildren = {
  StudentCoursesSlugLessonsLessonIdRoute:
    StudentCoursesSlugLessonsLessonIdRoute,
}

const StudentCoursesRouteWithChildren = StudentCoursesRoute._addFileChildren(
  StudentCoursesRouteChildren,
)

interface StudentRouteChildren {
  StudentCoursesRoute: typeof StudentCoursesRouteWithChildren
  StudentProfileRoute: typeof StudentProfileRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCoursesRoute: StudentCoursesRouteWithChildren,
  StudentProfileRoute: StudentProfileRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoursesRoute: CoursesRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  AuthPhoneRoute: AuthPhoneRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
