/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth.verify-otp'
import { Route as AuthPhoneRouteImport } from './routes/auth.phone'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as StudentCoursesIndexRouteImport } from './routes/student.courses.index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin.courses.index'
import { Route as AdminCoursesNewRouteImport } from './routes/admin.courses.new'
import { Route as AdminCoursesCourseIdRouteImport } from './routes/admin.courses.$courseId'
import { Route as AdminCoursesCourseIdIndexRouteImport } from './routes/admin.courses.$courseId.index'
import { Route as AdminCoursesCourseIdSettingsRouteImport } from './routes/admin.courses.$courseId.settings'
import { Route as AdminCoursesCourseIdContentRouteImport } from './routes/admin.courses.$courseId.content'
import { Route as StudentCoursesSlugLessonsLessonIdRouteImport } from './routes/student.courses.$slug.lessons.$lessonId'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/auth/verify-otp',
  path: '/auth/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPhoneRoute = AuthPhoneRouteImport.update({
  id: '/auth/phone',
  path: '/auth/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesIndexRoute = StudentCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentCoursesRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesNewRoute = AdminCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesCourseIdRoute = AdminCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesCourseIdIndexRoute =
  AdminCoursesCourseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminCoursesCourseIdRoute,
  } as any)
const AdminCoursesCourseIdSettingsRoute =
  AdminCoursesCourseIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminCoursesCourseIdRoute,
  } as any)
const AdminCoursesCourseIdContentRoute =
  AdminCoursesCourseIdContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AdminCoursesCourseIdRoute,
  } as any)
const StudentCoursesSlugLessonsLessonIdRoute =
  StudentCoursesSlugLessonsLessonIdRouteImport.update({
    id: '/$slug/lessons/$lessonId',
    path: '/$slug/lessons/$lessonId',
    getParentRoute: () => StudentCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/profile': typeof StudentProfileRoute
  '/courses/': typeof CoursesIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRouteWithChildren
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/student/courses/': typeof StudentCoursesIndexRoute
  '/admin/courses/$courseId/content': typeof AdminCoursesCourseIdContentRoute
  '/admin/courses/$courseId/settings': typeof AdminCoursesCourseIdSettingsRoute
  '/admin/courses/$courseId/': typeof AdminCoursesCourseIdIndexRoute
  '/student/courses/$slug/lessons/$lessonId': typeof StudentCoursesSlugLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/student/profile': typeof StudentProfileRoute
  '/courses': typeof CoursesIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/student/courses': typeof StudentCoursesIndexRoute
  '/admin/courses/$courseId/content': typeof AdminCoursesCourseIdContentRoute
  '/admin/courses/$courseId/settings': typeof AdminCoursesCourseIdSettingsRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdIndexRoute
  '/student/courses/$slug/lessons/$lessonId': typeof StudentCoursesSlugLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/profile': typeof StudentProfileRoute
  '/courses/': typeof CoursesIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRouteWithChildren
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/student/courses/': typeof StudentCoursesIndexRoute
  '/admin/courses/$courseId/content': typeof AdminCoursesCourseIdContentRoute
  '/admin/courses/$courseId/settings': typeof AdminCoursesCourseIdSettingsRoute
  '/admin/courses/$courseId/': typeof AdminCoursesCourseIdIndexRoute
  '/student/courses/$slug/lessons/$lessonId': typeof StudentCoursesSlugLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/courses'
    | '/student'
    | '/auth/login'
    | '/auth/phone'
    | '/auth/verify-otp'
    | '/courses/$slug'
    | '/student/courses'
    | '/student/profile'
    | '/courses/'
    | '/student/'
    | '/admin/courses/$courseId'
    | '/admin/courses/new'
    | '/admin/courses/'
    | '/student/courses/'
    | '/admin/courses/$courseId/content'
    | '/admin/courses/$courseId/settings'
    | '/admin/courses/$courseId/'
    | '/student/courses/$slug/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth/login'
    | '/auth/phone'
    | '/auth/verify-otp'
    | '/courses/$slug'
    | '/student/profile'
    | '/courses'
    | '/student'
    | '/admin/courses/new'
    | '/admin/courses'
    | '/student/courses'
    | '/admin/courses/$courseId/content'
    | '/admin/courses/$courseId/settings'
    | '/admin/courses/$courseId'
    | '/student/courses/$slug/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/courses'
    | '/student'
    | '/auth/login'
    | '/auth/phone'
    | '/auth/verify-otp'
    | '/courses/$slug'
    | '/student/courses'
    | '/student/profile'
    | '/courses/'
    | '/student/'
    | '/admin/courses/$courseId'
    | '/admin/courses/new'
    | '/admin/courses/'
    | '/student/courses/'
    | '/admin/courses/$courseId/content'
    | '/admin/courses/$courseId/settings'
    | '/admin/courses/$courseId/'
    | '/student/courses/$slug/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPhoneRoute: typeof AuthPhoneRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/auth/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/phone': {
      id: '/auth/phone'
      path: '/auth/phone'
      fullPath: '/auth/phone'
      preLoaderRoute: typeof AuthPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses/': {
      id: '/student/courses/'
      path: '/'
      fullPath: '/student/courses/'
      preLoaderRoute: typeof StudentCoursesIndexRouteImport
      parentRoute: typeof StudentCoursesRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/new': {
      id: '/admin/courses/new'
      path: '/courses/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AdminCoursesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/$courseId': {
      id: '/admin/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AdminCoursesCourseIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/$courseId/': {
      id: '/admin/courses/$courseId/'
      path: '/'
      fullPath: '/admin/courses/$courseId/'
      preLoaderRoute: typeof AdminCoursesCourseIdIndexRouteImport
      parentRoute: typeof AdminCoursesCourseIdRoute
    }
    '/admin/courses/$courseId/settings': {
      id: '/admin/courses/$courseId/settings'
      path: '/settings'
      fullPath: '/admin/courses/$courseId/settings'
      preLoaderRoute: typeof AdminCoursesCourseIdSettingsRouteImport
      parentRoute: typeof AdminCoursesCourseIdRoute
    }
    '/admin/courses/$courseId/content': {
      id: '/admin/courses/$courseId/content'
      path: '/content'
      fullPath: '/admin/courses/$courseId/content'
      preLoaderRoute: typeof AdminCoursesCourseIdContentRouteImport
      parentRoute: typeof AdminCoursesCourseIdRoute
    }
    '/student/courses/$slug/lessons/$lessonId': {
      id: '/student/courses/$slug/lessons/$lessonId'
      path: '/$slug/lessons/$lessonId'
      fullPath: '/student/courses/$slug/lessons/$lessonId'
      preLoaderRoute: typeof StudentCoursesSlugLessonsLessonIdRouteImport
      parentRoute: typeof StudentCoursesRoute
    }
  }
}

interface AdminCoursesCourseIdRouteChildren {
  AdminCoursesCourseIdContentRoute: typeof AdminCoursesCourseIdContentRoute
  AdminCoursesCourseIdSettingsRoute: typeof AdminCoursesCourseIdSettingsRoute
  AdminCoursesCourseIdIndexRoute: typeof AdminCoursesCourseIdIndexRoute
}

const AdminCoursesCourseIdRouteChildren: AdminCoursesCourseIdRouteChildren = {
  AdminCoursesCourseIdContentRoute: AdminCoursesCourseIdContentRoute,
  AdminCoursesCourseIdSettingsRoute: AdminCoursesCourseIdSettingsRoute,
  AdminCoursesCourseIdIndexRoute: AdminCoursesCourseIdIndexRoute,
}

const AdminCoursesCourseIdRouteWithChildren =
  AdminCoursesCourseIdRoute._addFileChildren(AdminCoursesCourseIdRouteChildren)

interface AdminRouteChildren {
  AdminCoursesCourseIdRoute: typeof AdminCoursesCourseIdRouteWithChildren
  AdminCoursesNewRoute: typeof AdminCoursesNewRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoursesCourseIdRoute: AdminCoursesCourseIdRouteWithChildren,
  AdminCoursesNewRoute: AdminCoursesNewRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface StudentCoursesRouteChildren {
  StudentCoursesIndexRoute: typeof StudentCoursesIndexRoute
  StudentCoursesSlugLessonsLessonIdRoute: typeof StudentCoursesSlugLessonsLessonIdRoute
}

const StudentCoursesRouteChildren: StudentCoursesRouteChildren = {
  StudentCoursesIndexRoute: StudentCoursesIndexRoute,
  StudentCoursesSlugLessonsLessonIdRoute:
    StudentCoursesSlugLessonsLessonIdRoute,
}

const StudentCoursesRouteWithChildren = StudentCoursesRoute._addFileChildren(
  StudentCoursesRouteChildren,
)

interface StudentRouteChildren {
  StudentCoursesRoute: typeof StudentCoursesRouteWithChildren
  StudentProfileRoute: typeof StudentProfileRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCoursesRoute: StudentCoursesRouteWithChildren,
  StudentProfileRoute: StudentProfileRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthPhoneRoute: AuthPhoneRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
